### ISSUE TITLE
Add missing dependency

### ISSUE THREAD

**Issue by Sander-Kastelein** [excell-mobility/scheduling_service#7]
Hi,

I'm trying to build the scheduling_service using maven on Ubuntu 18.04 with Oracle Java 1.8.0_171 but am missing the "excellapis" dependency.
Maven will display the following:

> [INFO] Scanning for projects...
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Building tourenplanung 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [WARNING] The POM for excell:excellapis:jar:0.0.1-SNAPSHOT is missing, no dependency information available
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.366 s
> [INFO] Finished at: 2018-07-15T10:54:21+02:00
> [INFO] Final Memory: 14M/34M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project tourenplanung: Could not resolve dependencies for project excell:tourenplanung:jar:0.0.1-SNAPSHOT: Failure to find excell:excellapis:jar:0.0.1-SNAPSHOT in https://repo.spring.io/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> 

I couldn't find any resources for a excellapis on your github account nor on Google.
Is  there any chance this dependency will become available so that I will be able to build this project?

Danke sehr

**Comment by FxKu** [comment]
Hey there,
I can send the missing JAR to you. Just text me via mail. We maintain the project in a private repo for some reasons.
But, your issue is a good hint, that this essential part is not documentated. I'll fix it and hopefully make the repo public soon.

**Comment by FxKu** [comment]
I received a mail. Name is very differnet - is it you? ;)
I've already refactored some critical parts in the excellapis project, but I need to find a good way to allow a user to load config properties dynamically. As default URLs for the web services I would use the ExCELL URLs, but this requires some for more work on the code. So, you have to wait a few more days. Sorry.

**Comment by FxKu** [comment]
Still, you could test the services on our [developer portal](https://www.excell-mobility.de/developer/). Are you already registered?

**Comment by Sander-Kastelein** [comment]
Hi again,

I didn't send an e-mail, I decided for this project to go another route and implement an own optimizer using graphhopper/jspirit and distance matrices from OSRM since it would give me more flexibility which I need for my use-case. (time-window, multiple vehicle types, limited vehicles, dynamic + static service date, priority constraints, skill constraints, employee-customer blacklist, employee-customer whitelist) 
This project still looks interesting to me though because it's a low barrier entry point for solving VRP and other kind of optimization problems. I might want to use it in future projects if/when fully available. But for now I will be studying optimization theory.

Thanks for answering regardless, I do hope I will be able to use this wrapper some day for future projects.

**Comment by FxKu** [comment]
To let you know, I have removed the excellapis dependency like in the routing project. As said in the other [issue](https://github.com/excell-mobility/routing_service/issues/5) you would need to adjust the URLs in the `application.properties`.
